// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function GetSettings():Promise<main.ReminderSettings>;

export function GetState():Promise<main.AppState>;

export function HideToTray():Promise<void>;

export function Quit():Promise<void>;

export function Reset():Promise<void>;

export function SetEnabled(arg1:boolean):Promise<void>;

export function ShowMainWindow():Promise<void>;

export function Skip():Promise<void>;

export function UpdateSettings(arg1:main.ReminderSettings):Promise<void>;
